version: '3.7'
services:
  sql_server:
    image: microsoft/mssql-server-linux
    container_name: sql_server
    environment:
      SA_PASSWORD: P@ssw0rd123!
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"